<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Консультант</title>
</head>
<body style="background: lightblue">
<h1 align="middle" style="margin: 100px">Консультант</h1>
<div class="wrapper">
    <a class="btn btn-success" href="/consultant/book">Сведения о книгах</a>
    <a class="btn btn-success" href="/consultant/contract">Сведения о договорах</a>
    <a class="btn btn-success" href="/consultant/manuscript">Сведения о рукописях</a>
    <a style="margin-top: 40px" href="/" class="btn btn-danger">Выход</a>
</div>
</body>
<style>
    .wrapper{
        background: #5A1C6E;
        border: 1px solid black;
        display: flex;
        width: 20%;
        justify-content: center;
        justify-items: center;
        flex-direction: column;
        align-items: center;
        margin: 0 auto;
        height: 40vh;
        padding: 10px;
    }
    .wrapper > a{
        margin: 10px;
        width: 100%;
    }
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

</html>