<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Издательство</title>
</head>
<body>
    <h2 align = center> Издательство </h2>
<div class="wrapper">
    <a class="btn btn-success" href="/redactor">Редактор</a>
    <a class="btn btn-success"  href="/consultant">Консультант</a>
    <a class="btn btn-success"  href="/manager">Менеджер</a>
</div>
</body>
<style>
    .wrapper{
        display: flex;
        width: 100%;
        justify-content: center;
        justify-items: center;
    }
    .wrapper > a{
        margin: 10px;
    }
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</html>