<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Consultant page</title>
</head>
<body>
<div class="wrapper">
    <a class="btn btn-success" href="/" class="btn btn-danger">Выход</a>
    <a class="btn btn-success" href="/consultant/book">Книги</a>
    <a class="btn btn-success" href="/consultant/client">Клиенты</a>
    <a class="btn btn-success" href="/consultant/contract">Контракты</a>
    <a class="btn btn-success" href="/consultant/manuscript">Рукописи</a>
    <a class="btn btn-success" href="/consultant/order">Заказы</a>
    <a class="btn btn-success" href="/consultant/writer">Писатели</a>
</div>
</body>
<style>
    .wrapper{
        display: flex;
        width: 100%;
        justify-content: center;
        justify-items: center;
    }
    .wrapper > a{
        margin: 10px;
    }
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

</html>